<main role="main">
<select name="ui_language" id="ui_language" class="lang_select">
    <option value="english" {php} if(LANGUAGE=="english") echo "selected";{/php} >English</option>
    <option value="russian" {php} if(LANGUAGE=="russian" || LANGUAGE=="ukrainian") echo "selected";{/php} >Русский</option>
</select>
{php} if (LANGUAGE=="russian" || LANGUAGE=="ukrainian") { {/php}
<h1>Политика конфиденциальности сайта {$CCMAINTITLE}</h1>
<p>Администрация сайта {$CCMAINTITLE} обязуется сохранять вашу конфиденциальность в Интернете. Мы уделяем большое значение охране предоставленных вами данных. Наша политика конфиденциальности основана на требованиях <a href="https://ec.europa.eu/info/law/law-topic/data-protection_en">Общего регламента о защите персональных данных Европейского Союза (GDPR)</a>. Цели, в которых мы собираем персональные данные: улучшение работы нашего сервиса, осуществление контактов с посетителями данного сайта, осуществление услуг, связанных с направлением деятельности данного сайта, а так же для указанных ниже действий.</p>
<h2>Сбор и использование персональных данных</h2>
<p>Мы собираем и используем ваши персональные данные только в случае вашего добровольного согласия. При согласии с этим вы разрешаете нам собирать и использовать следующие данные: имя и фамилия, электронная почта, номер телефона, домашний адрес, данные аккаунтов в социальных сетях. Сбор и обработка ваших данных проводится в соответствии с законами, действующими на территории Европейского Союза и в государстве Израиль.</p>
<h2>Хранение данных, изменение и удаление</h2>
<p>Пользователь, предоставивший свои персональные данные сайту {$CCMAINTITLE} имеет право на их изменение и удаление, а так же на отзыв своего согласия с их использованием. Срок, в течение которого будут храниться ваши персональные данные: время, необходимое для использования данных для основной деятельности сайта. При завершении использования ваших данных администрация сайта удаляет их. Для доступа к своим персональным данным вы можете обратиться к администрации сайта на электронную почту <a href="mailto:{$MAILTO}">{$MAILTO}</a>. Мы можем передавать ваши личные данные третьей стороне только с вашего добровольного согласия. Если они были переданы, то изменение данных в других организациях, не связанных с нами, мы осуществить не можем.</p>
<h2>Использование технических данных при посещении сайта</h2>
<p>При посещении вами сайта {$CCMAINTITLE} в базе данных сохраняются записи о вашем IP адресе, времени посещения, настройках браузера, операционной системе, а также другая техническая информация необходимая для корректного отображения содержимого сайта. По этим данным нам невозможно идентифицировать личность посетителя.</p>
<h2>Предоставление информации детьми</h2>
<p>Если Вы являетесь родителем или опекуном, и вы знаете, что ваши дети предоставили нам свои личные данные без Вашего согласия, свяжитесь с нами: <a href="mailto:{$MAILTO}">{$MAILTO}</a>. На нашем сервисе запрещено оставлять личные данные несовершеннолетних без согласия родителей или опекунов.</p>
<h2>Использование cookies</h2>
<p>Для корректного отображения содержимого и для удобства использования сайта {$CCMAINTITLE} мы используем cookie файлы. Это небольшие файлы, которые хранятся на вашем устройстве. Они помогают сайту запомнить информацию о вас, например на каком языке вы просматриваете сайт и какие страницы вы уже открывали, эта информация будет полезна при следующем посещении. Благодаря файлам cookie просмотр сайта становится значительно более удобным. Подробнее про эти файлы вы можете <a href="https://ru.wikipedia.org/wiki/Cookie">прочитать тут</a>. Вы можете настроить прием или блокировку cookie в браузере самостоятельно. Невозможность принимать cookie может ограничить работоспособность сайта.</p>
<h2>Использование персональных данных другими сервисами</h2>
<p>На этом сайте используются сторонние интернет-сервисы, осуществляющие независимый от нас сбор информации: Google Analytics, Google AdSense, Disqus.com, Facebook.com, Liveinternet.ru. Собранные ими данные могут предоставляться другим службам внутри этих организаций, они могут использовать данные для персонализации рекламы своей собственной рекламной сети.  Вы можете прочитать пользовательские соглашения этих организаций на их сайтах. Там же вы можете отказаться от сбора ими персональных данных, к примеру блокировщик Google Analytics находится <a href="https://tools.google.com/dlpage/gaoptout?hl=ru">тут</a>, блокировщик Яндекс Метрики <a href="https://yandex.ru/support/metrika/general/opt-out.html">тут</a>. Мы не передаем персональные данные другим организациям и службам, не указанным в данной политике конфиденциальности. Исключение составляет только передача информации при законных требованиях государственных органов уполномоченных осуществлять данные действия.</p>
<h2>Ссылки на другие сайты</h2>
<p>Наш сайт {$CCMAINTITLE} может содержать ссылки на другие сайты, которые не управляются нами. Мы не несем ответственность за их содержание. Мы рекомендуем вам ознакомиться с политикой конфиденциальности каждого сайта, который вы посещаете, если она там есть.</p>
<h2>Изменения в политике конфиденциальности</h2>
<p>Наш сайт {$CCMAINTITLE} может обновлять нашу политику конфиденциальности время от времени. Мы сообщаем о любых изменениях, разместив новую политику конфиденциальности на этой странице. Мы отслеживаем изменения законодательства, касающегося персональных данных в Европейском Союзе и в государстве Israel. Если вы оставили персональные данные у нас, то мы оповестим вас об изменении в политике конфиденциальности. Если ваши персональные данные были введены не корректно, то мы не сможем с вами связаться.</p>
<h2>Обратная связь, заключительные положения</h2>
<p>Связаться с администрацией сайта {$CCMAINTITLE} по вопросам, связанным с политикой конфиденциальности можно через кабинет по адресу <a href="{$CUSTOMER_INTERFACE_URL}support">{$CUSTOMER_INTERFACE_URL}support</a>, либо с помощью контактной формы указанной в соответствующем разделе данного сайта. Если вы не согласны с данной политикой конфиденциальности, вы не можете пользоваться услугами сайта {$CCMAINTITLE}, в этом случае вы должны воздержаться от посещения нашего сайта.</p>
{php}}else{{/php}
<h1>Privacy and Data Policy of {$CCMAINTITLE}</h1>
<p>{$CCMAINTITLE} website administration is obliged to maintain your privacy on the Internet. We pay great attention to securing the data you provided to us. Our privacy policy is based on <a href="https://ec.europa.eu/info/law/law-topic/data-protection_en">the General Data Protection Regulation (GDPR) of the European Union</a>. The purposes, for which we collect your personal data are: improvement of our service, communication with visitors to this site, newsletters, user data processing for the purpose of online sales, presenting the information requested by the user, providing services associated with the website’s specialization and for other actions listed below.</p>
<h3>Personal data storage and processing</h3>
<p>We collect and process your personal data only with your willing consent. With your permission, we can collect and process the following data: name and surname, e-mail address, phone number, home address, social media account information. Collection and processing of your personal information is carried out in accordance with the laws of the European Union and the Israel.</p>
<h3>Data storage, alteration, and removal</h3>
<p>The user, who has provided {$CCMAINTITLE} with their personal data, has the right for their alteration and removal, as well as the right to recall the agreement to data processing. Time, during which your personal data will be stored is: time the personal data is used that is necessary for the website’s main activity. After finishing with the processing of your personal data, the website’s administration will permanently delete it. To access your personal data, you can contact the administration on: <a href="mailto:{$MAILTO}">{$MAILTO}</a>. We will be able to pass your data to a third party only with your willing consent. If the data was transferred to a third party, which is not associated with our organization, we cannot perform any changes to that data.</p>
<h3>Processing of visiting technical data</h3>
<p>Records of your IP address, time of visit, browser settings, operational system and other technical information is saved in the database when you visit {$CCMAINTITLE}. This data is necessary for the correct display of the website’s content. It is impossible to identify the person of the visitor using this data.</p>
<h3>Children’s personal information</h3>
<p>If you are a parent or a legal guardian of an underage child, and you know that the child has provided us with their personal information without your consent, please contact us on: <a href="mailto:{$MAILTO}">{$MAILTO}</a>. It is forbidden to enter personal data of underage users without the agreement of parents or lawful guardians.</p>
<h3>Cookies processing</h3>
<p>We use cookie files for the correct display of the website’s content and for the convenience of browsing {$CCMAINTITLE}. They are small files, that are stored on your device. They help the website to remember information about you, such as in which language you use the website and which pages have you already opened. This information will be useful in the next visit. Thanks to cookie files, the website’s browsing becomes much more convenient. You can learn more about these files <a href="https://en.wikipedia.org/wiki/HTTP_cookie">here</a>. You can set up cookies reception and blocking in your browser yourself. Inability to receive cookie files may limit the functionality of the website.</p>
<h3>Processing of personal data by other services</h3>
<p>This website uses third-party online services, which perform data collecting, independent from us. Such services include: Google Analytics , Google AdSense, Disqus.com, Facebook.com, Liveinternet.ru.</p>
<p>Data collected by these services may be provided to other services within those organizations. They can use the data for advertising personalization of their own advertising network. You can learn about user agreements of those organizations on their websites. You can also refuse their collection of your personal data. For example, Google Analytics Opt-out Browser Add-on can be found <a href="https://tools.google.com/dlpage/gaoptout?hl=en"> here</a>. We do not pass any personal data to other organizations or services, which are not listed in this privacy policy. As an exception, the collected data may be provided on a lawful request of state authorities, that are authorized to request such information.</p>
<h3>Links to other websites</h3>
<p>Our website {$CCMAINTITLE} may contain links to other websites, which are not under our control. We are not responsible for the content of these websites. We recommend you familiarize yourself with the privacy policy of every website that you visit, if such policy exists.</p>
<h3>Changes to the privacy policy</h3>
<p>From time to time, our website {$CCMAINTITLE} may update our privacy policy. We inform about any changes to the privacy policy, placed on this webpage. We are monitoring any changes in legislation, which is related to personal data in European Union and Israel. If you have entered any of your personal data on our website, we will inform you about the changes in our privacy policy. If your personal data, and more specifically, your contact information  was entered incorrectly, we will not be able to contact you.</p>
<h3>Feedback and final clauses</h3>
<p>You can contact the administration of {$CCMAINTITLE} regarding any questions related to privacy policy on: in the cabinet at <a href="{$CUSTOMER_INTERFACE_URL}support">{$CUSTOMER_INTERFACE_URL}support</a>, or by e-mail to <a href="mailto:{$MAILTO}">{$MAILTO}</a>, or by filling a contact form specified in a corresponding section of this website. If you do not agree with this privacy policy, you cannot use the services of {$CCMAINTITLE}. In this case you should avoid visiting our website.</p>
{php}}{/php}
<br><br>
</main>
