<main role="main">
{php} if (false && (LANGUAGE=="russian" || LANGUAGE=="ukrainian")) { {/php}

{php}}else{{/php}
<h1>Terms &amp; conditions</h1>
<h3>The {$CCMAINTITLE} Subscriber Agreement</h3>
<p>{$CCMAINTITLE}{if (false)} Ltd, trading as {$CCMAINTITLE},{/if} provides VoIP services to customers in accordance with the terms and conditions set forth in this agreement.</p>
<p>By registering for, activating, making use of, or by paying for {$CCMAINTITLE}’s site or services you acknowledge having read and agreed to these terms, and you represent that there is no legal impediment to your entering or being bound by this agreement.</p>
<h3>Billing, Pricing and Charges</h3>
<p>Usage of {$CCMAINTITLE}’s services will be charged according to the current price list as made available on the {$CCMAINTITLE} site. Changes to our pricing shall become effective immediately upon posting to the site.</p>
<p>{$CCMAINTITLE} accepts no liability for any charges assessed by a third party provider when used in conjunction with {$CCMAINTITLE}'s services. Your access to and use of a service provided by a third party provider is subject to the provider's terms and conditions. As soon as your call is connected to a phone number provided by {$CCMAINTITLE}, the call may be charged regardless of whether you are connected to the receiver of the call.</p>
<p>The rates that will be charged for calls will be based on a rate which is exclusive of any applicable taxes and surcharges. This rate will be the rate advertised on the {$CCMAINTITLE} website at the time of the call.</p>
<p>Cost of call calculation will be based on the length of the call rounded up to the next nearest full minute.</p>
<p>Payment for {$CCMAINTITLE}’s services is billed on a pre-pay basis, unless otherwise agreed by both parties. You agree that our services will not be provisioned until sufficient pre-payment has been made, and that service may be terminated immediately if sufficient pre-payment has not been made. It is your ongoing responsibility to ensure that your account maintains the necessary balance to provision the service.</p>
<p>Refunds will only be made for orders within 90 days of completion. No refunds of less than 3&#128; will be made against each order. Refunds are subject to an administration fee of the greater of 10% or 1&#128;.</p>
<p>You agree that {$CCMAINTITLE} can expire any credit that remains unused for a rolling period of 365 days. Such expiration renders the balance non-refundable.</p>
<p>Customers are limited to a single active subscription to any one destination within a billing period. We reserve the right to cancel subscriptions and accounts without refunding unused minutes where we suspect users have created multiple accounts to circumvent this limit.</p>
<h3>Measuring Usage</h3>
<p>You agree that {$CCMAINTITLE}’s records are conclusive evidence of your use of the site and service. Furthermore, you acknowledge that these records will be used to calculate charges incurred.</p>
<p>You agree to be held fully responsible for all use of and fees related to your account, and accept full liability and responsibility for the actions of anyone who uses the site or service via your account, whether authorised or unauthorised, except when unauthorised use is solely attributed to an act or omission on the part of {$CCMAINTITLE}.</p>
<p>You agree that {$CCMAINTITLE} should not be and is not responsible for any third party claims against us that arise from your use of the Service. Further, you agree to reimburse us for all of our costs and expenses related to the defence of any such claims, including legal fees, unless such claims are based on our wilful misconduct or gross negligence.</p>
<p>You must notify {$CCMAINTITLE} within thirty (30) days of the date on your credit card or debit card statement if you dispute any {$CCMAINTITLE} charges on that statement or such dispute will be deemed waived.</p>
<p>Incoming numbers are meant for average retail customer use and will be restricted to 2 incoming concurrent calls. This means that high volumes of incoming calls are not allowed. Incoming numbers are not to be used for call centers or business use where a large amount of incoming calls come in to each number. There will be a 0.01&#128; surcharge assessed on a per call basis for each call to any incoming number that exceeds 100 calls per day per number.</p>
<h3>Internet Phone (VOIP)</h3>
<p>The Service requires Equipment, or software obtained through {$CCMAINTITLE} or a third party, that allows you to place and receive calls by using your high-speed Internet connection. {$CCMAINTITLE} does not provide or support your high-speed Internet connection, which you need to supply at your own expense. We recommend that your high-speed connection have a capacity of at least 120 Kbps upstream and downstream.</p>
<p>Since the Service depends on your high-speed connection, the correct configuration of the Equipment, and an adequate power supply, {$CCMAINTITLE} does not guarantee continuous availability. You acknowledge and understand that the Service will not function in the absence of electrical power or if there is an interruption of your high-speed Internet connection. A power failure may require you to reset or reconfigure your Equipment or other equipment in order to restore the Service.</p>
<p>You understand and acknowledge that the Service may not be compatible with all non-voice communications equipment, including but not limited to, home security systems, medical monitoring equipment, fax machines, satellite television systems, and computer modems. You waive any claim against {$CCMAINTITLE} for interference or disruption of such services and equipment.</p>
<h3>Free Test Calls</h3>
<p>Free test calls are provided at the discretion of {$CCMAINTITLE} and can be withdrawn at anytime. 5 minutes worth of calls will be added to your account upon the successful completion of registration and after all information requested has been provided.</p>
<p>If a call has been previously made from a telephone or account registered on our website no free credit will be given.</p>
<p>Destinations included in the free test call promotion will be totally at the discretion of {$CCMAINTITLE}. Not all destinations will be included in the promotion and can change at anytime without notice.</p>
<p>Credit will expire 60 days from account creation if it has not been used. Your free call will be removed if you add credit before making your free call.</p>
<h3>Unlimited Calling Plan</h3>
<p>For customers purchasing an unlimited calling plan the following terms apply:</p>
<p>The billing cycle starts on 1st of month and runs for a complete month.</p>
<p>Customers purchasing a plan part-way through the month will be asked to make a pro-rated payment and may be asked to cover the cost of the following month up-front.</p>
<p>Subscription payments will be taken in advance monthly 7 days prior to the end of the month.</p>
<p>If we can’t take payment within the 7 days prior to the end of the month your unlimited service plan will be cancelled. To re-activate your Subscription you’ll be required to pay the set-up fee again.</p>
<p>You may cancel your Subscription at any point. The cancellation will take place at your next billing date. No refunds are available for this product.</p>
<p>Once you have purchased an unlimited calling plan for a specific number it’s not possible to change the number. To add a new number you’ll need to cancel your existing plan and start a new one (set-up fee will be incurred).</p>
<p>No refunds are available for partially completed months.</p>
<h3>Liability &amp; Indemnification</h3>
<p>You agree to indemnify {$CCMAINTITLE} and its agents, and hold them harmless from any claims or damages relating to this agreement. You agree not to hold {$CCMAINTITLE} or its agents liable for any loss of business, contracts, savings or profits, or any other damages or losses (direct or consequential) to the extent that {$CCMAINTITLE}’s liability can be limited by law.</p>
<p>You are expressly prohibited from using the Service or Equipment for any abusive or fraudulent purpose, including using the Service in a way that interferes with our ability to provide the Service to you or other customers or avoids your obligation to pay for communications services.</p>
<p>{$CCMAINTITLE}, in its sole discretion, may terminate your Service without advance notice if it believes you have violated the aforementioned restrictions, or if you act in a manner that is threatening, obscene, harassing, or abusive to {$CCMAINTITLE} personnel. {$CCMAINTITLE} may pass along fees or costs that it incurs from authorities, government agencies, carriers, or other partners in regards to the use of services.</p>
<p>You are liable for any and all use of the Service by any person using the Service provided to you and agree to indemnify and hold harmless {$CCMAINTITLE} against any and all liability for any such use. If {$CCMAINTITLE}, in its sole discretion, believes that you have violated the aforementioned restrictions, {$CCMAINTITLE} may forward personally identifiable information to the appropriate authorities for investigation and prosecution and you hereby consent to such forwarding.</p>
<p>You are expressly prohibited from any use of the Service or any other action that, in {$CCMAINTITLE}’s sole discretion, is deemed to present a risk to the network integrity or security of {$CCMAINTITLE} or its vendors, whether directly or indirectly. {$CCMAINTITLE}, in its sole discretion, may terminate your Service without advance notice if it determines your actions could cause a network disruption or security breach.</p>
<h3>Term of and Changes to This Agreement</h3>
<p>The terms of this agreement shall come into effect immediately upon appearing on the {$CCMAINTITLE} website, as indicated by the time-stamp at the foot of this document. {$CCMAINTITLE} may terminate this agreement at any time for any breach of these terms or any applicable policy as posted on the {$CCMAINTITLE} website. No reimbursement for any fees charged in connection with {$CCMAINTITLE}’s services shall be issued for such a termination.</p>
<p>Any provision of this agreement relating to term, payment, liability, indemnification, governing law, or confidentiality shall survive termination or expiration.</p>
<h3>Assignment</h3>
<p>We can assign all or part of our rights or duties under this Agreement without notifying you. If we do that, we have no further obligations to you. You may not assign this Agreement or the Service without our prior written consent.</p>
<h3>Privacy</h3>
<p>{$CCMAINTITLE} Service utilises, in whole or in part, the public Internet and third party networks to transmit voice and other communications. {$CCMAINTITLE} is not liable for any lack of privacy which may be experienced with regard to the Service. In addition, {$CCMAINTITLE} will provide personally identifiable customer and call detail information in response to lawful government requests, subpoenas, and court orders, as well as law enforcement requests. Please refer to our Privacy Policy applicable to you on the {$CCMAINTITLE} web-site for additional information.</p>
<h3>Notices</h3>
<p>{$CCMAINTITLE} primarily communicates with users of the Service via email. Email from {$CCMAINTITLE} is used to communicate important information about the Service, including billing and changes to the Service, much of which is time-sensitive. {$CCMAINTITLE} reserve the right to withdraw any service offered by the company immediately without prior warning or notice. You acknowledge that email from {$CCMAINTITLE} constitutes official notice from {$CCMAINTITLE} and that you are required to read in a timely manner all email messages sent to the email address specified by you at the time of registration for the Service in order to avoid any potential disruption of the Service. You also acknowledge that you are responsible for notifying {$CCMAINTITLE} of any changes in your email address.</p>
<h3>General Provisions</h3>
<p>{$CCMAINTITLE} will not be responsible to you for any delay, failure in performance, loss, or damage due to fire, explosion, power blackout, earthquake, volcanic action, flood, the weather elements, strike, embargo, labour disputes, civil or military authority, war, acts of God, acts or omissions of carriers or suppliers, acts of regulatory or governmental agencies, or other causes beyond our reasonable control.</p>
<h3>Porting</h3>
<p>Availability for porting phone numbers to or from {$CCMAINTITLE}, and any administrative and processing fees incurred for the porting, depend on a number’s country and current network provider. Please provide details of the number(s) you wish to port to or away from {$CCMAINTITLE} to <a href="mailto:{$MAILTO}">{$MAILTO}</a> and we will advise you of any costs involved.</p>
<br>
{php}}{/php}
</main>